Repository KEA-5th-Myaong/frontend, pull requests merged in 2024-10, with the labels that each got.

#4 KAN-82-블로그페이지레이아웃제작
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_components/PostComment.tsx
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_components/PostDropDown.tsx
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_components/testComment.json
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_types/post.ts
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/page.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/PostContainer.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/UserProfile.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/_follow/FollowButton.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/_follow/FollowModal.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/_follow/follow.json
  src/app/(route)/(blog)/blog/[userId]/_components/test.json
  src/app/(route)/(blog)/blog/[userId]/_types/blog.ts
  src/app/(route)/(blog)/blog/[userId]/layout.tsx
  src/app/(route)/(blog)/blog/[userId]/page.tsx
  src/app/(route)/(interview)/_components/InterviewHistory.tsx
  src/app/(route)/(interview)/interview/[id]/select/page.tsx
  src/app/_components/BackButton.tsx
  src/app/_components/Post.tsx
  src/app/_components/UserProfile.tsx
  src/app/_components/ui/Icon.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_hooks/useClickOutside.ts
  src/app/_types/icon.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#5 KAN-85-모의면접
  src/app/(route)/(interview)/_components/InterviewHistory.tsx
  src/app/(route)/(interview)/_components/ProgressBar.tsx
  src/app/(route)/(interview)/_hooks/useContainerHeight.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/_components/MessageForm.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/page.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/PersonalStatementBox.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/QuestionBox.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/personalStatement.json
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/question.json
  src/app/(route)/(interview)/interview/[id]/[corp]/_types/corp.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/_utils/listVariants.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/personal-statement/page.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/question/page.tsx
  src/app/(route)/(interview)/interview/[id]/select/page.tsx
  src/app/(route)/(interview)/layout.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_hooks/useScrollToBottom.ts
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#6 Kan-79-랜딩페이지
  package-lock.json
  package.json
  public/assets/landing-page/blue-background.svg
  public/assets/landing-page/ic-eye.svg
  public/assets/landing-page/ic-lightning.svg
  public/assets/landing-page/img-orange-circle.svg
  public/assets/landing-page/landing-light.svg
  public/assets/landing-page/section1-img.svg
  public/assets/landing-page/section1-img2.svg
  public/assets/landing-page/section2-img1.svg
  public/assets/landing-page/section3-img1.svg
  public/assets/landing-page/section3-img2-sm.svg
  public/assets/landing-page/section3-img2.svg
  public/assets/landing-page/section4-back.svg
  public/assets/landing-page/section4-front.svg
  public/assets/landing-page/section4-img1.svg
  public/assets/landing-page/section4-img2.svg
  public/assets/landing-page/section5.svg
  public/assets/logo-lg.svg
  public/assets/logo-sm.svg
  src/app/(route)/layout.tsx
  src/app/(route)/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  tailwind.config.ts
Labels: 서연, ✨ 작업 완료, 📌 확인 요청

#7 KAN-106-자소서목록
  package-lock.json
  package.json
  public/mascot.png
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/page.tsx
  src/app/(route)/(personal-statement)/_components/PSFooter.tsx
  src/app/(route)/(personal-statement)/_components/PSHeader.tsx
  src/app/(route)/(personal-statement)/_store/psStore.ts
  src/app/(route)/(personal-statement)/layout.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/create/_components/PSCreateContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/create/_components/PSForm.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/create/_types/psCreate.ts
  src/app/(route)/(personal-statement)/personal-statement/[id]/create/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/editing/_components/PSEditingBox.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/editing/_components/PSEditingContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/editing/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListBox.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListHeader.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PStest.json
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_types/psList.ts
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/preview/_components/PSPreviewContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/preview/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/_components/PSReadContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/_components/PSReadContent.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/_components/psReadTest.json
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/page.tsx
  src/app/_components/BackButton.tsx
  src/app/_components/Modal.tsx
  src/app/_components/MoreOptions.tsx
  src/app/_components/Overlay.tsx
  src/app/_types/common.ts
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#8 Kan-112-포트폴리오목록
  .eslintrc.json
  public/assets/add-button.svg
  src/app/(route)/(portfolio)/_components/PortfolioAddCard.tsx
  src/app/(route)/(portfolio)/_components/PortfolioCard.tsx
  src/app/(route)/(portfolio)/_components/PortfolioDropdown.tsx
  src/app/(route)/(portfolio)/portfolio/page.tsx
  src/app/(route)/(portfolio)/portfolio/write/page.tsx
  src/app/_store/portfolio.ts
  src/app/_types/portfolio.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 서연, ✨ 작업 완료, 📌 확인 요청

#9 KAN-117-마이페이지
  src/app/(route)/(Login_SignUp)/_components/FormInput.tsx
  src/app/(route)/(Login_SignUp)/_types/forms.ts
  src/app/(route)/(my-page)/_components/MyPageHeader.tsx
  src/app/(route)/(my-page)/layout.tsx
  src/app/(route)/(my-page)/my-page/change-password/_components/ChangePwdContainer.tsx
  src/app/(route)/(my-page)/my-page/change-password/page.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/ChangeProfileContainer.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/ImageChange.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/JobSelection.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/jobTest.json
  src/app/(route)/(my-page)/my-page/change-profile/_types/myPage.ts
  src/app/(route)/(my-page)/my-page/change-profile/page.tsx
  src/app/(route)/(my-page)/my-page/check-password/_components/CheckPwdContainer.tsx
  src/app/(route)/(my-page)/my-page/check-password/page.tsx
  src/app/(route)/(my-page)/my-page/withdraw/_components/WithdrawContainer.tsx
  src/app/(route)/(my-page)/my-page/withdraw/page.tsx
  src/app/_components/Modal.tsx
  src/app/_components/ui/iconPath.ts
  src/app/globals.css
  tailwind.config.ts
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#10 KAN-115-Header
  public/LOGO(PC).png
  public/LOGO(Tablet).png
  public/LOGO(mobile).png
  public/assets/header/bell.svg
  src/app/(route)/layout.tsx
  src/app/_components/Header.tsx
  src/app/_components/ui/iconPath.ts
  tailwind.config.ts
Labels: 지연, ✨ 작업 완료, 📌 확인 요청

#11 Kan-127-메인페이지레이아웃
  public/assets/carousel1.png
  src/app/(route)/(Login_SignUp)/log-in/_components/LoginForm.tsx
  src/app/(route)/(blog)/blog/[userId]/[postTitle]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/UserProfile.tsx
  src/app/(route)/(blog)/blog/[userId]/_components/test.json
  src/app/(route)/(blog)/blog/[userId]/_types/blog.ts
  src/app/(route)/(main-page)/main/_components/JobMenu.tsx
  src/app/(route)/(main-page)/main/_components/jobMenuTest.json
  src/app/(route)/(main-page)/main/page.tsx
  src/app/_components/Post.tsx
  src/app/_components/ui/iconPath.ts
  tailwind.config.ts
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#13 Kan 129 포스트작성
  src/app/(route)/(blog)/blog/[userId]/write/_components/PostInput.tsx
  src/app/(route)/(blog)/blog/[userId]/write/page.tsx
Labels: 지연, feat, ✨ 작업 완료, 📌 확인 요청

#14 Kan-124-포트폴리오작성
  package-lock.json
  public/assets/ic-delete.svg
  src/app/(route)/(portfolio)/_components/PortfolioAddCard.tsx
  src/app/(route)/(portfolio)/_components/PortfolioCard.tsx
  src/app/(route)/(portfolio)/_components/PortfolioDropdown.tsx
  src/app/(route)/(portfolio)/portfolio/page.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Footer.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Input.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/ItemToggle.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/PortfolioWriteDropdown.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Toggle.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/ActivityItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/CertificationItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/EducationItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/ExperienceItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/LinkItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/ActivitiesSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/CertificationsSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/EducationSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/ExperienceSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/LinksSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/PSSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/SkillsSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/page.tsx
  src/app/_components/MotionWrapper.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_store/portfolioToggle.ts
  src/app/globals.css
Labels: 서연, feat, ✨ 작업 완료, 📌 확인 요청

#16 Kan-125-포트폴리오조회
  public/profile.png
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/_components/PSReadContainer.tsx
  src/app/(route)/(portfolio)/_components/Footer.tsx
  src/app/(route)/(portfolio)/_components/PortfolioWriteDropdown.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/preview/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/_components/PortfolioContainer.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/_components/PortfolioHeader.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/Input.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/ItemToggle.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/Toggle.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/UploadImage.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/ActivityItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/CertificationItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/EducationItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/ExperienceItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/LinkItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/ActivitiesSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/CertificationsSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/EducationSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/ExperienceSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/LinksSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/PSSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/SkillsSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/page.tsx
  src/app/(route)/(portfolio)/portfolio/page.tsx
  src/app/(route)/(portfolio)/portfolio/write/page.tsx
  src/app/globals.css
Labels: 서연, feat, ✨ 작업 완료, 📌 확인 요청

#17 Kan 132 백지연/프로토타입
  public/LOGO(PC).png
  public/LOGO(Tablet).png
  public/LOGO(mobile).png
  public/assets/logo-md.svg
  src/app/(route)/layout.tsx
  src/app/_components/Header.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/_components/MainMenu.tsx
  src/app/_components/Header/_components/MyMenu.tsx
  src/app/_components/Header/_components/SideMenu.tsx
  src/app/_components/Header/_components/SubMenu.tsx
  src/app/_components/Header/menuData.json
  src/app/_components/Header/test.json
  src/app/globals.css
Labels: 지연, ✨ 작업 완료, 📌 확인 요청

#19 KAN-146-멤버api연결
  package-lock.json
  package.json
  src/app/(route)/(blog)/blog/[memberId]/[postTitle]/_components/_comment/PostComment.tsx
  src/app/(route)/(blog)/blog/[memberId]/[postTitle]/_components/_comment/testComment.json
  src/app/(route)/(blog)/blog/[memberId]/[postTitle]/_types/post.ts
  src/app/(route)/(blog)/blog/[memberId]/_components/_follow/follow.json
  src/app/(route)/(blog)/blog/[memberId]/_components/test.json
  src/app/(route)/(blog)/blog/[memberId]/_hooks/useComments.ts
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/_comment/CommentItem.tsx
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/_comment/EditCommentInput.tsx
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/_comment/PostComment.tsx
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/_comment/ReplyInput.tsx
  src/app/(route)/(blog)/blog/[username]/[postId]/_types/post.ts
  src/app/(route)/(blog)/blog/[username]/[postId]/page.tsx
  src/app/(route)/(blog)/blog/[username]/_components/PostContainer.tsx
  src/app/(route)/(blog)/blog/[username]/_components/UserProfile.tsx
  src/app/(route)/(blog)/blog/[username]/_components/_follow/FollowButton.tsx
  src/app/(route)/(blog)/blog/[username]/_components/_follow/FollowModal.tsx
  src/app/(route)/(blog)/blog/[username]/_services/blogService.ts
  src/app/(route)/(blog)/blog/[username]/_types/blog.ts
  src/app/(route)/(blog)/blog/[username]/layout.tsx
  src/app/(route)/(blog)/blog/[username]/page.tsx
  src/app/(route)/(blog)/blog/[username]/write/page.tsx
  src/app/(route)/(main-page)/main/_components/PostFeed.tsx
  src/app/(route)/(main-page)/main/_services/mainService.ts
  src/app/(route)/(main-page)/main/_types/main-page.ts
  src/app/_components/Header/menuData.json
  src/app/_utils/formatDate.ts
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#21 KAN-148-모의면접api연결
  src/app/(route)/(interview)/_components/InterviewHistory.tsx
  src/app/(route)/(interview)/_components/ProgressBar.tsx
  src/app/(route)/(interview)/_services/interviewService.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_components/MessageForm.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_components/MsgEditBtn.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_types/messageType.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/page.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/QuestionBox.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/interviewPSBox.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/personalStatement.json
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/question.json
  src/app/(route)/(interview)/interview/[id]/[corp]/_store/interviewStore.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/_types/corp.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/personal-statement/page.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/question/page.tsx
  src/app/(route)/(interview)/interview/[id]/select/page.tsx
  src/app/(route)/(interview)/layout.tsx
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#20 KAN-145-자소서api연결
  src/app/(route)/(personal-statement)/personal-statement/[id]/create/_components/PSCreateContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/editing/_components/PSEditingContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListBox.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_types/psList.ts
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/_components/PSReadContainer.tsx
Labels: 지연, ✨ 작업 완료, 📌 확인 요청

#22 KAN-165-프로토타입마무리
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/personal-statement/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/editing/_components/PSEditingContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/preview/_components/PSPreviewContainer.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/UploadImage.tsx
Labels: 지연, ✨ 작업 완료, 📌 확인 요청
