Repository KEA-5th-Myaong/frontend, pull requests merged in 2024-11, with the labels that each got.

#23 KAN-170-모의면접
  public/assets/videoImage.png
  src/app/(route)/(blog)/blog/[username]/write/page.tsx
  src/app/(route)/(interview)/_components/InterviewHistory.tsx
  src/app/(route)/(interview)/_components/ProgressBar.tsx
  src/app/(route)/(interview)/_hooks/useContainerHeight.ts
  src/app/(route)/(interview)/_services/interviewService.ts
  src/app/(route)/(interview)/_store/interviewStore.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/[questionId]/chat/_utils/messageVariants.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/_components/QuestionBox.tsx
  src/app/(route)/(interview)/interview/[id]/[corp]/_store/interviewStore.ts
  src/app/(route)/(interview)/interview/[id]/[corp]/question/page.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/_components/interviewPSBox.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/_types/corp.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/_utils/interviewVariants.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/_utils/listVariants.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/MessageForm.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/MsgEditBtn.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/TailNewBtn.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/Video.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_types/messageType.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/page.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/personal-statement/page.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/tutorial/_components/ToolTip.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/tutorial/page.tsx
  src/app/(route)/(interview)/interview/[username]/history/[title]/page.tsx
  src/app/(route)/(interview)/interview/[username]/select/page.tsx
  src/app/_components/Header/menuData.json
  src/app/_components/ui/Icon.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_store/chatWrite.ts
  src/app/_store/postWirte.ts
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#26 KAN-195-약관동의페이지
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  public/assets/admin/main-admin.svg
  public/assets/admin/main-contents.svg
  public/assets/admin/main-faq.svg
  public/assets/admin/main-membercategory.svg
  public/assets/adminLogo.svg
  public/assets/arrow-right.svg
  src/app/(admin-route)/(admin)/admin/_components/AdminSideBar.tsx
  src/app/(admin-route)/(admin)/admin/_components/reportTest.json
  src/app/(admin-route)/(admin)/admin/contents/page.tsx
  src/app/(admin-route)/(admin)/admin/page.tsx
  src/app/(admin-route)/layout.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/Video.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/tutorial/page.tsx
  src/app/(route)/(log-in_sign-up)/change-pwd/_components/ChangePwdForm.tsx
  src/app/(route)/(log-in_sign-up)/change-pwd/page.tsx
  src/app/(route)/(log-in_sign-up)/log-in/page.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/page.tsx
  src/app/(route)/(log-in_sign-up)/terms-of-use/_data/terms.ts
  src/app/(route)/(log-in_sign-up)/terms-of-use/layout.tsx
  src/app/(route)/(log-in_sign-up)/terms-of-use/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListBox.tsx
  src/app/_components/Post.tsx
  src/app/_components/ui/iconPath.ts
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#27 KAN-212-관리자상세
  public/assets/admin/main-contents.svg
  public/assets/admin/main-faq.svg
  public/assets/admin/main-membercategory.svg
  src/app/(admin-route)/(admin)/admin/_components/AdminSideBar.tsx
  src/app/(admin-route)/admin/_components/AdminModal.tsx
  src/app/(admin-route)/admin/_components/AdminSideBar.tsx
  src/app/(admin-route)/admin/_components/reportTest.json
  src/app/(admin-route)/admin/_types/admin-types.ts
  src/app/(admin-route)/admin/contents/page.tsx
  src/app/(admin-route)/admin/layout.tsx
  src/app/(admin-route)/admin/page.tsx
  src/app/_components/Modal.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_types/common.ts
  src/app/_types/icon.ts
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#28 KAN-181-문의공지페이지
  src/app/(route)/(help)/notice/[noticeId]/select/page.tsx
  src/app/(route)/(help)/notice/layout.tsx
  src/app/(route)/(help)/notice/list/page.tsx
  src/app/(route)/(help)/notice/test.json
  src/app/(route)/(help)/qa/[inquiryId]/select/page.tsx
  src/app/(route)/(help)/qa/layout.tsx
  src/app/(route)/(help)/qa/list/page.tsx
  src/app/(route)/(help)/qa/test.json
  src/app/(route)/(help)/qa/write/page.tsx
  src/app/_components/ui/iconPath.ts
  tailwind.config.ts
Labels: 지연, feat, ✨ 작업 완료, 📌 확인 요청

#29 KAN-224-블로그
  package-lock.json
  package.json
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[username]/[postId]/_components/_comment/PostComment.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/CommentItem.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/EditCommentInput.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/PostComment.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/ReplyInput.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_types/post.ts
  src/app/(route)/(blog)/blog/[username]/[postTitle]/page.tsx
  src/app/(route)/(blog)/blog/[username]/_components/PostContainer.tsx
  src/app/(route)/(blog)/blog/[username]/_components/UserProfile.tsx
  src/app/(route)/(blog)/blog/[username]/_services/blogService.ts
  src/app/(route)/(blog)/blog/[username]/_types/blog.ts
  src/app/(route)/(blog)/blog/[username]/write/page.tsx
  src/app/(route)/(main-page)/main/_components/PostFeed.tsx
  src/app/(route)/(main-page)/main/_types/main-page.ts
  src/app/_components/MoreOptions.tsx
  src/app/_components/Post.tsx
  src/app/_components/ToastEditor.tsx
  src/app/_hooks/useCustomInfiniteQuery.ts
  src/app/_hooks/useLoveAndBookmark.ts
  src/app/_hooks/useWindowHeight.tsx
  src/app/_store/postWirte.ts
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#24 Kan-143-포트폴리오 form 처리, 자기소개서 모달 추가
  package-lock.json
  package.json
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/Input.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/ItemToggle.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/LoadPSModal.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/Tips.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/ActivityItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/CertificationItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/EducationItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/ExperienceItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/items/LinkItem.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/portfolioTips.json
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/ActivitiesSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/CertificationsSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/EducationSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/ExperienceSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/LinksSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/PSSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/section/SkillsSection.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/page.tsx
  src/app/(route)/(portfolio)/portfolio/page.tsx
  src/app/(route)/page.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_types/portfolio.ts
  src/app/globals.css
Labels: 서연, ✨ 작업 완료

#33 영상 제출용 수정사항 반영
  package-lock.json
  src/app/(admin-route)/admin/_services/adminService.ts
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/PostComment.tsx
  src/app/(route)/(blog)/blog/[username]/_components/PostContainer.tsx
  src/app/(route)/(blog)/blog/[username]/_components/_follow/FollowModal.tsx
  src/app/(route)/(main-page)/main/_components/InterestedJob.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/editing/_components/PSEditingContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/read/_components/PSReadContainer.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/_components/PortfolioContainer.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/page.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_store/portfolio.ts
Labels: 현중, ✨ 작업 완료, 📌 확인 요청
