Repository KEA-5th-Myaong/frontend, pull requests merged in 2024-12, with the labels that each got.

#36 KAN-233-관리자기업관리
  src/app/(admin-route)/admin/corp/page.tsx
Labels: 지연, ✨ 작업 완료, 📌 확인 요청

#34 KAN-246-블로그추가개발
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[username]/_components/PostContainer.tsx
  src/app/(route)/(blog)/blog/[username]/_services/blogService.ts
  src/app/(route)/(log-in_sign-up)/_types/forms.ts
  src/app/(route)/(log-in_sign-up)/log-in/_components/LoginForm.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/_components/SignUpForm.tsx
  src/app/(route)/(main-page)/main/_components/InterestedJob.tsx
  src/app/(route)/(main-page)/main/_components/JobMenu.tsx
  src/app/(route)/(main-page)/main/_components/PostFeed.tsx
  src/app/(route)/(main-page)/main/_services/mainService.ts
  src/app/(route)/(main-page)/main/_types/main-page.ts
  src/app/(route)/(main-page)/main/layout.tsx
  src/app/(route)/(main-page)/main/page.tsx
  src/app/(route)/(main-page)/main/search/page.tsx
  src/app/_components/Header/_components/MyMenu.tsx
  src/app/_services/membersService.ts
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#37 Kan-244-포트폴리오 API 연결 및 리팩토링
  next.config.mjs
  src/app/(route)/(blog)/blog/[username]/_services/blogService.ts
  src/app/(route)/(my-page)/my-page/change-profile/_components/ImageChange.tsx
  src/app/(route)/(personal-statement)/personal-statement/[id]/list/_components/PSListHeader.tsx
  src/app/(route)/(portfolio)/_components/PortfolioCard.tsx
  src/app/(route)/(portfolio)/_components/PortfolioDropdown.tsx
  src/app/(route)/(portfolio)/_services/portfolioServices.ts
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/modify/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/preview/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/_components/PortfolioHeader.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/LoadPSModal.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/write/_components/UploadImage.tsx
  src/app/(route)/(portfolio)/portfolio/page.tsx
  src/app/(route)/(portfolio)/portfolio/preview/PortfolioContainer.tsx
  src/app/(route)/(portfolio)/portfolio/preview/page.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Input.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/ItemToggle.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/LoadPSModal.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Tips.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Toggle.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/UploadImage.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/ActivityItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/CertificationItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/EducationItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/ExperienceItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/items/LinkItem.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/portfolioTips.json
  src/app/(route)/(portfolio)/portfolio/write/_components/section/ActivitiesSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/CertificationsSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/EducationSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/ExperienceSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/LinksSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/PSSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/section/SkillsSection.tsx
  src/app/(route)/(portfolio)/portfolio/write/page.tsx
  src/app/_store/portfolio.ts
  src/app/_types/portfolio.ts
Labels: 서연, ✨ 작업 완료, 📌 확인 요청

#40 KAN-258-블로그유저연결
  package-lock.json
  package.json
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/PostContent.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/CommentItem.tsx
  src/app/(route)/(blog)/blog/[username]/[postTitle]/_components/_comment/PostComment.tsx
  src/app/(route)/(blog)/blog/[username]/_components/PostContainer.tsx
  src/app/(route)/(blog)/blog/[username]/_components/UserProfile.tsx
  src/app/(route)/(blog)/blog/[username]/_components/_follow/FollowModal.tsx
  src/app/(route)/(blog)/blog/[username]/_services/blogService.ts
  src/app/(route)/(blog)/blog/[username]/write/page.tsx
  src/app/(route)/(interview)/_components/InterviewHistory.tsx
  src/app/(route)/(interview)/_services/interviewService.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/_components/interviewPSBox.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/Video.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_types/messageType.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/page.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/tutorial/page.tsx
  src/app/(route)/(interview)/interview/[username]/history/[title]/page.tsx
  src/app/(route)/(log-in_sign-up)/_components/FormInput.tsx
  src/app/(route)/(log-in_sign-up)/_constants/forms.ts
  src/app/(route)/(log-in_sign-up)/_types/forms.ts
  src/app/(route)/(log-in_sign-up)/_utils/validation.ts
  src/app/(route)/(log-in_sign-up)/change-pwd/_components/ChangePwdForm.tsx
  src/app/(route)/(log-in_sign-up)/log-in/_components/LoginForm.tsx
  src/app/(route)/(log-in_sign-up)/log-in/_components/SocialLogin.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/_components/SignUpDetailForm.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/_components/SignUpForm.tsx
  src/app/(route)/(main-page)/main/_components/MainTabMenu.tsx
  src/app/(route)/(main-page)/main/_components/PostFeed.tsx
  src/app/(route)/(main-page)/main/_types/main-page.ts
  src/app/(route)/(main-page)/main/page.tsx
  src/app/(route)/(main-page)/main/search/page.tsx
  src/app/(route)/(my-page)/_components/MyPageHeader.tsx
  src/app/(route)/(my-page)/layout.tsx
  src/app/(route)/(my-page)/my-page/change-password/_components/ChangePwdContainer.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/ChangeProfileContainer.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/ImageChange.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_components/JobSelection.tsx
  src/app/(route)/(my-page)/my-page/change-profile/_types/myPage.ts
  src/app/(route)/(my-page)/my-page/check-password/_components/CheckPwdContainer.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/_components/MainMenu.tsx
  src/app/_components/Header/_components/MyMenu.tsx
  src/app/_components/Header/_components/SideMenu.tsx
  src/app/_components/Header/_components/SubMenu.tsx
  src/app/_components/Header/menuData.json
  src/app/_components/Post.tsx
  src/app/_components/ui/iconPath.ts
  src/app/_hooks/useLoveAndBookmark.ts
  src/app/_services/membersService.ts
  src/app/_store/chatWrite.ts
  src/app/globals.css
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#41 KAN-262-자소서CRUD
  src/app/(route)/(personal-statement)/_components/PSHeader.tsx
  src/app/(route)/(personal-statement)/_services/psServices.ts
  src/app/(route)/(personal-statement)/_store/psStore.ts
  src/app/(route)/(personal-statement)/personal-statement/[id]/create/_components/PSCreateContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/create/_components/PSCreateContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/create/_components/PSForm.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/create/_types/psCreate.ts
  src/app/(route)/(personal-statement)/personal-statement/[username]/create/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/editing/_components/PSEditingBox.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/editing/_components/PSEditingContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/editing/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_components/PSListBox.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_components/PSListContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_components/PSListHeader.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_components/PStest.json
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_types/psList.ts
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/preview/_components/PSPreviewContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/preview/page.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/read/_components/PSReadContainer.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/read/_components/PSReadContent.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/read/_components/psReadTest.json
  src/app/(route)/(personal-statement)/personal-statement/[username]/read/page.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/LoadPSModal.tsx
  src/app/_components/ui/iconPath.ts
Labels: 지연, feat, ✨ 작업 완료, 📌 확인 요청

#44 Kan-267-알림 API 연결 및 헤더 수정
  src/app/_components/Header/_components/Alarm.tsx
  src/app/_components/Header/_components/MyMenu.tsx
  src/app/_components/Header/_components/SubMenu.tsx
  src/app/_components/Header/_types/notifications.ts
  src/app/_components/Header/test.json
  src/app/_components/ui/iconPath.ts
  src/app/_services/notificationsService.ts
Labels: 서연, feat, ✨ 작업 완료, 📌 확인 요청

#50 KAN-260-캐러셀
  package-lock.json
  package.json
  public/assets/banner/banner-button-1.svg
  public/assets/banner/banner-button-2.svg
  public/assets/banner/banner-button-3.svg
  public/assets/banner/banner-pf-img.svg
  public/assets/banner/banner-ps-img.svg
  public/assets/carousel2.jpg
  public/assets/carousel3.jpg
  src/app/(route)/(main-page)/main/_components/Carousel.tsx
  src/app/(route)/(main-page)/main/layout.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_components/PSBanner.tsx
  src/app/(route)/(personal-statement)/personal-statement/[username]/list/_components/PSListContainer.tsx
  src/app/(route)/(portfolio)/_components/PortfolioBanner.tsx
  src/app/(route)/(portfolio)/portfolio/page.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 서연, ✨ 작업 완료, 📌 확인 요청

#51 KAN-278-다크모드미적용페이지
  public/assets/log-in/kakao-login.png
  src/app/(route)/(log-in_sign-up)/log-in/_components/LoginForm.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/_components/SignUpForm.tsx
Labels: 지연, ✨ 작업 완료, 📌 확인 요청

#55 KAN-280-1차수정
  src/app/(route)/(blog)/blog/[username]/_components/PostContainer.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_types/messageType.ts
  src/app/(route)/(main-page)/main/_components/EmptyStateMessage.tsx
  src/app/_components/Header/_components/Alarm.tsx
  src/app/_components/Header/_components/SideMenu.tsx
  src/app/_components/ui/iconPath.ts
Labels: 지연, ✨ 작업 완료

#54 KAN-282-1차QA2
  src/app/(route)/(blog)/blog/[username]/_components/UserProfile.tsx
  src/app/(route)/(blog)/blog/[username]/_components/_follow/FollowModal.tsx
  src/app/_components/Header/_components/SideMenu.tsx
Labels: 현중, ✨ 작업 완료, 📌 확인 요청

#57 KAN-286-1차QA3
  src/app/(route)/(interview)/_store/interviewStore.ts
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/ChatContainer.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_components/Video.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/personal-statement/page.tsx
  src/app/(route)/(interview)/interview/[username]/history/[title]/page.tsx
  src/app/(route)/(log-in_sign-up)/change-pwd/_components/ChangePwdForm.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/_components/SignUpDetailForm.tsx
  src/app/(route)/(log-in_sign-up)/sign-up/_components/SignUpForm.tsx
  src/app/(route)/(log-in_sign-up)/terms-of-use/page.tsx
  src/app/(route)/(my-page)/my-page/check-password/_components/CheckPwdContainer.tsx
  src/app/(route)/(my-page)/my-page/withdraw/_components/WithdrawContainer.tsx
  src/app/(route)/(portfolio)/_components/PortfolioCard.tsx
  src/app/(route)/(portfolio)/_services/portfolioServices.ts
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/modify/page.tsx
  src/app/(route)/(portfolio)/portfolio/[portfolioId]/read/page.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/Input.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/LoadPSModal.tsx
  src/app/(route)/(portfolio)/portfolio/write/_components/UploadImage.tsx
  src/app/(route)/page.tsx
  src/app/_components/ui/PageWrapper.tsx
Labels: 현중, feat, ✨ 작업 완료, 📌 확인 요청

#58 KAN-288-2차QA
  src/app/(admin-route)/admin/_components/AdminSideBar.tsx
  src/app/(admin-route)/admin/corp/page.tsx
  src/app/(admin-route)/admin/corp/test.json
  src/app/(admin-route)/admin/page.tsx
  src/app/(route)/(interview)/interview/[username]/[corp]/chat/_types/messageType.ts
  src/app/_components/Header/_components/MyMenu.tsx
Labels: 현중, feat, 작업 중
